#reconciliator services
reconciliators:
  - name: ASIA (Wikifier)
    prefix: asiaWk
    #Cambia nome url myServerUrl (es)
    relativeUrl: /asia/wikifier 
    uri: 
    metaToViz: 
      #possibilità di cambiare i nomi alle label dell"header
      - id
      - name
      - score
      - match
  - name: ASIA (Geonames)
    prefix: geo
    relativeUrl: /asia/geonames
    uri: http://www.geonames.org/
    metaToViz: 
      - id
      - name
      - score
      - match
  - name: ASIA (Keywords Matcher)
    prefix: asiaKM
    relativeUrl: /asia/keywordsmatcher 
    uri:
    metaToViz: 
      - id
      - name
      - score
      - match
  - name: Wikidata
    prefix: "wkd"
    relativeUrl: /wikidata
    uri: https://www.wikidata.org/wiki/
    metaToViz: 
      - id
      - name
      - score
      - match
  - name: LamAPI
    prefix: lmp
    relativeUrl: /lamapi
    uri:
    metaToViz: 
      - id
      - name
      - score
      - match

# Extension services
extenders:
  - id: 4DIX1FKTWc6avs7XPBAbe
    serviceKey: asiaGeo
    name: ASIA (geonames)
    relativeUrl: /asia/geonames
    description: "ASIA extension service based on geonames allows to extend a column with data on locations of a certain administrative order, given a column reconciliated with First-order administrative division ids."
    formParams:
      - id: property
        description: "Select on or more <b>Property</b> values:"
        label: "Property"
        inputType: checkbox # select / selectColumns / checkbox / text
        rules: ["required"]
        options:
          - id: adm1
            label: "First-order administrative division (Regions or States)"
            value: "parentADM1"
          - id: adm2
            label: "Second-order administrative division (Provinces)"
            value: "parentADM2"
          - id: adm3
            label: "Third-order administrative division (Communes)"
            value: "parentADM3"
          - id: adm4
            label: "Fourth-order administrative division"
            value: "parentADM4"
  - id: wnfp58G33OytB9KQr6BS0
    serviceKey: asiaWeather
    name: Weather
    relativeUrl: /asia/weather
    description: "ASIA weather-based extension service allows to extend a column with meteorological data for given locations and dates."
    formParams:
      - id: dates
        description: "Select a column for <b>Dates</b> values:"
        label: "Dates"
        infoText: "Only date for the years between 2017 and 2019 and German regions are supported (ISO format yyyy-mm-dd)"
        inputType: selectColumns # select / selectColumns / checkbox / text
        rules: ["required"]

      - id: weatherParams
        description: "Select one or more <b>Weather</b> parameters:"
        label: "Weather parameters"
        infoText: "Meteorological parameter with which you want to extend the table"
        inputType: checkbox # select / selectColumns / checkbox / text
        rules: ["required"]
        options:
          - id: "ws"
            value: "ws"
            label: "Wind speed"
          - id: "2t"
            value: "2t"
            label: "2 metre temperature"
          - id: "2d"
            value: "2d"
            label: "2 metre dewpoint temperature"
          - id: "sund"
            value: "sund"
            label: "Sunshine duration"
      
      - id: "offsets"
        description: "Enter desired <b>Offsets</b>:"
        label: "Offset"
        infoText: "The offset is the difference in days for which we want to retrieve the data with respect to the input dates. You can add multiple offsets separated by a COMMA"
        inputType: text # select / selectColumns / checkbox / text
        defaultValue: "0"
        rules: ["required"]
            