version: "3.6"
services:
  server:
    build: 
      context: .
      dockerfile: dev.dockerfile
    env_file: .env
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - "3002:3002"