version: "3.6"
services:
  release:
    image: "ghcr.io/i2tunimib/i2t:latest"
    env_file: .env
    volumes:
      - /datahdd/asia/I2T-backend/saved:/usr/src/app/public/saved
      - /datahdd/asia/I2T-backend/tables:/usr/src/app/public/tables
    ports:
      - "3002:3002"
