export default {
  private: {
    endpoint: "",
    processRequest: true,
  },
  public: {
    name: "Text to columns / Columns to text",
    relativeUrl: "",
      description:
        "A transformation function that allows joining multiple columns into one or splitting a single column into " +
        "multiple columns using a separator defined by the user or by extracting the first or last portion of the cell value.",
      skipFiltering: true,
      formParams: [
        {
          id: "operationType",
          label: "Operation type",
          description: "Select the operation to perform on the selected columns.",
          inputType: "radio",
          rules: ["required"],
          options: [
            { id: "joinOp", label: "Join multiple columns into a single one", value: "joinOp" },
            { id: "splitOp", label: "Split a single column into multiple ones", value: "splitOp" },
          ],
        },
        {
          id: "columnToJoin",
          label: "Additional columns to join",
          description: "<strong>Optional:</strong> Specify one or more additional columns to include in the join operation, " +
            "in addition to the columns already selected in the main interface.",
          infoText: "",
          inputType: "multipleColumnSelect",
        },
        {
          id: "splitMode",
          label: "Split mode",
          description: "Choose how to split the selected column.",
          inputType: "radio",
          rules: ["required"],
          options: [
            { id: "separator", label: "Specifying a separator (e.g., comma, space)", value: "separator" },
            { id: "portion", label: "Extracting first or last token of the cell value", value: "portion" },
          ],
        },
        {
          id: "separator",
          label: "Separator",
          description: "Specify the separator to use for joining or splitting values.",
          infoText: "",
          inputType: "text",
          rules: ["required"],
        },
        {
          id: "extractPortion",
          label: "Extract",
          description: "Choose which portion of the cell value to extract, splitting the selected column into two columns.",
          inputType: "radio",
          rules: ["required"],
          options: [
            { id: "first", label: "First token (e.g., 'Mario' | 'Rossi 123456')", value: "first" },
            { id: "last", label: "Last token (e.g., 'Mario Rossi' | '123456')", value: "last" },
          ],
        },
        {
          id: "splitRenameMode",
          label: "Naming for split columns",
          description: "Choose the naming mode for the new generated columns.",
          inputType: "radio",
          rules: ["required"],
          options: [
            { id: "auto", label: "Use default names (e.g., columnName_1, columnName_2, etc.)", value: "auto" },
            { id: "custom", label: "Rename new columns", value: "custom" },
          ],
        },
        {
          id: "renameNewColumnSplit",
          label: "Rename new columns",
          description: "Specify a list of new column names separated by commas (e.g. full name, ID student).",
          infoText: "Provide one name for each column generated by the split operation.",
          inputType: "text",
          rules: ["required"],
        },
        {
          id: "renameJoinedColumn",
          label: "Rename joined column",
          description: "<strong>Optional:</strong> Specify a custom name for the resulting joined column. " +
            "If left blank, a default name in the format 'col1_col2' will be applied.",
          infoText: "",
          inputType: "text",
        },
      ],
  },
};
