export default {
  private: {
    endpoint: "",
    processRequest: true,
  },
  public: {
    group: "Gen AI",
    name: "LLM Modifier",
    relativeUrl: "",
    description:
      "A transformation service that allows to write a custom prompt to modify the values of a column ",
    skipFiltering: true,
    formParams: [
      {
        id: "operationType",
        label: "Operation type",
        description: "Select the operation to perform on the selected columns.",
        inputType: "radio",
        rules: ["required"],
        options: [
          {
            id: "joinOp",
            label: "Join multiple columns into a single one",
            value: "joinOp",
          },
          {
            id: "splitOp",
            label: "Split a single column into multiple ones",
            value: "splitOp",
          },
          {
            id: "inPlace",
            label: "Edit the column directly",
            value: "inPlace",
          },
        ],
      },
      {
        id: "columnToJoin",
        label: "Additional columns to join",
        description:
          "<strong>Optional:</strong> Specify one or more additional columns to include in the join operation, " +
          "in addition to the columns already selected in the main interface.",
        infoText: "",
        inputType: "multipleColumnSelect",
      },

      {
        id: "splitRenameMode",
        label: "Naming for split columns",
        description: "Choose the naming mode for the new generated columns.",
        inputType: "radio",
        rules: ["required"],
        options: [
          {
            id: "auto",
            label: "Use default names (e.g., columnName_1, columnName_2, etc.)",
            value: "auto",
          },
          { id: "custom", label: "Rename new columns", value: "custom" },
        ],
      },
      {
        id: "renameNewColumnSplit",
        label: "Rename new columns",
        description:
          "Specify a list of new column names separated by commas (e.g. full name, ID student).",
        infoText:
          "Provide one name for each column generated by the split operation.",
        inputType: "text",
        rules: ["required"],
      },
      {
        id: "renameJoinedColumn",
        label: "Rename joined column",
        description:
          "<strong>Optional:</strong> Specify a custom name for the resulting joined column. " +
          "If left blank, a default name in the format 'col1_col2' will be applied.",
        infoText: "",
        inputType: "text",
      },
      {
        id: "prompt",
        description:
          "Write instructions for how to modify the values of the cells.",
        label: "Reconciliation instructions",
        inputType: "textArea",
        rules: ["required"],
      },
    ],
  },
};
