export default {
  private: {
    endpoint: "",
    processRequest: true,
  },
  public: {
    group: "Gen AI",
    name: "Custom (LLM Modifier)",
    relativeUrl: "",
    description:
      "A flexible LLM-powered modification service that transforms column values based on a custom prompt. " +
      "Use the LLM to intelligently clean, normalize, rewrite, anonymize, extract or restructure data.<br><br>" +
      "<strong>Input</strong>: Column values to modify, the operation to perform and custom instructions describing how to modify them.<br>" +
      "<strong>Output</strong>: Updated column values, a new joined column, or multiple new columns generated by a split.<br><br>" +
      "<strong>How to use:</strong><br>" +
      "<ul style='list-style-type: decimal;'>" +
      "<li>Choose an operation type (Join / Split / Edit directly).</li>" +
      "<li>(Optional) Select additional columns for the join operation.</li>" +
      "<li>(Optional) Rename new generated columns for the join and split operation.</li>" +
      "<li>Write instructions describing how to modify the values. The LLM will receive each cell value and return output based on the operation type.</li>" +
      "</ul>" +
      "<strong>Example propmts:</strong><br>" +
      '<ul style="list-style-type: disc;">' +
      "<li>Join: <code>Merge first_name and last_name into a full name. Trim spaces and capitalize properly.</code></li>" +
      "<li>Split: <code>From 'address' extract street, city, and postal_code. Return values exactly as: street | city | postal_code.</code></li>" +
      "<li>Edit directly: <code>Standardize dates to ISO format (YYYY-MM-DD). If missing, return an empty string.</code></li>" +
      "</ul>",
    skipFiltering: true,
    formParams: [
      {
        id: "operationType",
        label: "Operation type",
        description: "Select the operation to perform on the selected columns.",
        inputType: "radio",
        rules: ["required"],
        options: [
          {
            id: "joinOp",
            label: "Join multiple columns into a single one",
            value: "joinOp",
          },
          {
            id: "splitOp",
            label: "Split a single column into multiple ones",
            value: "splitOp",
          },
          {
            id: "inPlace",
            label: "Edit the column directly",
            value: "inPlace",
          },
        ],
      },
      {
        id: "columnToJoin",
        label: "Additional columns to join",
        description:
          "<strong>Optional:</strong> Specify one or more additional columns to include in the join operation, " +
          "in addition to the columns already selected in the main interface.",
        infoText: "",
        inputType: "multipleColumnSelect",
        dependsOn: {
          field: "operationType",
          value: "joinOp",
        },
      },

      {
        id: "splitRenameMode",
        label: "Naming for split columns",
        description: "Choose the naming mode for the new generated columns.",
        inputType: "radio",
        rules: ["required"],
        options: [
          {
            id: "auto",
            label: "Use default names (e.g., columnName_1, columnName_2, etc.)",
            value: "auto",
          },
          { id: "custom", label: "Rename new columns", value: "custom" },
        ],
        dependsOn: {
          field: "operationType",
          value: "splitOp",
        },
      },
      {
        id: "renameNewColumnSplit",
        label: "Rename new columns",
        description:
          "Specify a list of new column names separated by commas (e.g. full name, ID student).",
        infoText:
          "Provide one name for each column generated by the split operation.",
        inputType: "text",
        rules: ["required"],
        dependsOn: {
          and: [
            { field: "operationType", value: "splitOp" },
            { field: "splitRenameMode", value: "custom" },
          ],
        },
      },
      {
        id: "renameJoinedColumn",
        label: "Rename joined column",
        description:
          "<strong>Optional:</strong> Specify a custom name for the resulting joined column. " +
          "If left blank, a default name in the format 'col1_col2' will be applied.",
        infoText: "",
        inputType: "text",
        dependsOn: {
          field: "operationType",
          value: "joinOp",
        },
      },
      {
        id: "prompt",
        description:
          "Write instructions for how to modify the values of the cells.",
        label: "Reconciliation instructions",
        inputType: "textArea",
        rules: ["required"],
      },
    ],
  },
};
